//
// Created by amice on 12/21/23.
//

#ifndef DRAKE_PLANNING_IRIS_IN_CONFIGURATION_SPACE_FROM_CLIQUE_COVER_H_
#define DRAKE_PLANNING_IRIS_IN_CONFIGURATION_SPACE_FROM_CLIQUE_COVER_H_

class iris_in_configuration_space_from_clique_cover {

};

#endif //DRAKE_PLANNING_IRIS_IN_CONFIGURATION_SPACE_FROM_CLIQUE_COVER_H_
